apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: guestbook
  namespace: guestbook
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - guestbook