apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: guestbook-sub-frontend
  namespace: guestbook
  labels:
    app: guestbook
spec:
  channel: cha1/guestbook
  overrides:
    - clusterName: /
      clusterOverrides:
        - path: metadata.namespace
          value: team1
  packageFilter:
    annotations:
      tier: frontend
  placement:
    placementRef:
      name: guestbook-placement
      kind: PlacementRule